name: Update Release Information

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
  workflow_call:

jobs:
  tag:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Create and push tag
        run: |
          NEW_VERSION=$((VERSION + 1))
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag "v${NEW_VERSION}"
          git push origin "v${NEW_VERSION}"
        env:
          VERSION: ${{ vars.VERSION }}

      - name: Update VERSION variable
        run: |
          NEW_VERSION=$((VERSION + 1))
          gh variable set VERSION --body "${NEW_VERSION}" --env github-pages
        env:
          VERSION: ${{ vars.VERSION }}
